### ISSUE TITLE
需要提供一个简单的方式判断 DbNull。

### ISSUE THREAD

**Issue by bunnier** [bunnier/sqlmer#5]

**Comment by cmstar** [comment]
目前的问题是，返回的结果比较不友好，并且有些情况在 API 上没有明确定义。

例如对于 `Scalar` 方法：
- 没有命中行：返回 `sql.ErrNoRows` 错误。
- 命中行，结果为 dbnull （数据库的 null ）：返回可变值，对于 varchar 返回 sql.NullString ，对于 int 返回 sql.NullInt 。
- 命中行，结果不是 dbnull ：返回对应值。

实际使用起来，调用者非常难以判定。

为了解决这个问题，思路上采用两种方式：
1. 对于 `MapScan` / `SliceScan` 等以行为输出单位的 API ：
    - 没有行时，返回的 map/slice 为 nil 。
    - 某个列值为 dbnull 时，统一使用 Go 的 nil 值表示。
2. 对于 `Scalar` 这样返回一个值的 API ：
    - 增加一个 bool 返回值表示是否有行。
    - 当有行时， 用 nil 表示 dbnull 。
    - error 仅留给执行错误，不会返回 `sql.ErrNoRows` 。

`Scalar` 添加一个 bool 值的形式，可参考 cmstar/sqlmer@065ab1e09 。

**Comment by bunnier** [comment]
在 v1.2.0 以上的 tag 中，已经按此方式处理，详见 @a93f468
